<?php

namespace App\Exceptions;

use Throwable;
use App\Traits\ApiResponse;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Validation\ValidationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

class Handler extends ExceptionHandler
{
    use ApiResponse;

    public function render($request, Throwable $e)
    {
        // ðŸ”¹ Para errores de validaciÃ³n (ya controlados en BaseFormRequest)
        if ($e instanceof ValidationException) {
            return $this->errorResponse(
                $e->errors(),
                'Errores de validaciÃ³n',
                422
            );
        }

        // ðŸ”¹ Cuando no encuentra un modelo
        if ($e instanceof ModelNotFoundException) {
            return $this->errorResponse(
                null,
                'Recurso no encontrado',
                404
            );
        }

        // ðŸ”¹ Cuando no estÃ¡ autenticado
        if ($e instanceof AuthenticationException) {
            return $this->errorResponse(
                null,
                'No autenticado',
                401
            );
        }

        // ðŸ”¹ Para cualquier otro error no manejado
        return $this->errorResponse(
            config('app.debug') ? $e->getMessage() : 'Error interno del servidor',
            'Error interno',
            500
        );
    }
}
